version: "3.8"

services:
  api:
    build: ./src
    image: carlosdan2/homevalued_api:latest
    environment:
      - SECRET_KEY = ${SECRET_KEY}
      - PGSQL_HOST = ${PGSQL_HOST}
      - PGSQL_USER = ${PGSQL_USER}
      - PGSQL_PASSWORD = ${PGSQL_PASSWORD}
      - PGSQL_DATABASE = ${PGSQL_DATABASE}
      - PGSQL_TABLENAME = ${PGSQL_TABLENAME}
    # env_file:
    #   - .env
    depends_on:
      - "db"
    ports:
      - 5002:5002
  db:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      
    # env_file:
    #   - .env.dev.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB} -t 1"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
    volumes:
      - ./database_file/homevalued_script_2.sql:/docker-entrypoint-initdb.d/homevalued_script_2.sql
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: